version: "3.8"

services:
  web:
    build:
      context: .
      dockerfile: Dockerfile.dev
    ports:
      - "3000:3000"
    volumes:
      # Sinkronisasi folder lokal dengan container untuk Hot-Reloading
      - .:/app
      # Mengecualikan node_modules lokal agar menggunakan node_modules dalam container (Mencegah error OS)
      - /app/node_modules
      - /app/.next
    environment:
      - NODE_ENV=development
      # Variabel ini penting di WSL agar Hot-Reloading Next.js berjalan lancar
      - WATCHPACK_POLLING=true
